name: IntelliJ Plugin Build
on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk23-corretto
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # required since test report action uses git
      - name: Configure Git Safe Directory
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          git config --global --add safe.directory "/__w/$REPO_NAME/$REPO_NAME"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          token: '${{ secrets.NPM_TOKEN }}'
          always-auth: true

      - name: Plugin Linting
        run: ./gradlew ktlintCheck

      - name: Plugin Tests
        run: ./gradlew test

      - name: Plugin Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Plugin Test Results
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit

      - name: Build plugin
        run: ./gradlew buildPlugin
