name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: context-mapper-intellij-plugin
          path: ./plugin
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./plugin/context-mapper-intellij-plugin.zip
